Eonasdan/tempus-dominus

src/js/bootstrap-datetimepicker.js
https://github.com/Eonasdan/bootstrap-datetimepicker/pull/748
=> BUGFIX: for KEY_ESC with Bootstrap Modal

src/js/bootstrap-datetimepicker.js
Change the viewDate value to move to the minDate or maxDate month if it is out of range
=> Fixes #777

CONTRIBUTING.md, src/js/bootstrap-datetimepicker.js
I improved the conditions to place the pickers: giving some safe margins to ensure that the widget doesn't go out the screen vertically or horizontally at any time; updating the conditions that define the picker's position; creating a fallback to fix the css('right') placement if the element is smaller than the parent.
=> Improv picker placement

src/js/bootstrap-datetimepicker.js
I have not been able to locate the original fix for #647 (or it regressed) so I am proposing this one.
=> Fix #647 (regression)

src/sass/_bootstrap-datetimepicker.scss, src/sass/bootstrap-datetimepicker-build.scss
Simply translated the less file. Basicly replaced `@` with `$`. It's not tested yet. I will do that tomorrow in a project I am working on. There should be no problems though, but you never know :)
#652
=> Translated LESS files to SASS (scss-version)

src/js/bootstrap-datetimepicker.js
I fixed horizontal position of picker. on left side you can see fixed picker and right side is resulte of develop branch. I tested result for both `right` and `left` in `widgetPositioning.horizontal`
```js
$('#right input').datetimepicker({
widgetPositioning:{
vertical: 'auto',
horizontal: 'right'
}
});
```
```js
$('#right input').datetimepicker({
widgetPositioning:{
vertical: 'auto',
horizontal: 'left'
}
});
```
=> fix horizental positioning

src/js/bootstrap-datetimepicker.js
enabledHours and disabledHours now try 24 times to find a valid hour.
=> fixes #974, certain sets of en/disabled hours break picker

src/js/bootstrap-datetimepicker.js
Disables period toggle if the hour being toggled to is disabled.
=> fixes #975, no longer possible to toggle onto a disabled hour

src/js/bootstrap-datetimepicker.js
That's my suggested fix for issue #726. All tests pass:
125 specs in 1.328s.
> 0 failures
=> Fixed lazy binding value bug

package.json
=> Fix jquery dependency

.travis.yml
* Faster travis run using containers: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
=> Improved travis.yml

src/js/bootstrap-datetimepicker.js
To make it consistent with the date picker.
=> Moved time picker tooltips to options.

docs/Options.md
Sorry about #1252
Guess that's why you shouldn't :beer: and code :D 
And... rtfd ;-) 
Non the less: here it is.
=> Add missing comma signs

src/js/bootstrap-datetimepicker.js
Add internationalization to 'Select Time' string
Replace 'Select Time' string to localize.
=> Add i18n to 'Select Time'

src/js/bootstrap-datetimepicker.js
Changed decades header to match what is shown.
Made decades view handle larger date range.
=> Couple changes to updateDecades()

src/js/bootstrap-datetimepicker.js
* jsFiddle with original datetimepicker.js: http://jsfiddle.net/hvm6u9m2/
* jsFiddle with modified datetimepicker.js: http://jsfiddle.net/a7tfx629/
=> The defaultDate was not showing when using a placeholder.

src/js/bootstrap-datetimepicker.js
Hi,
The change introduced by the ADM and CommonJS PR merge break code for others. This fixes it.
Jordane
=> Avoid breaking change on AMD and CommonJS support

Options/index.html
Adding new options tooltips that follows
* Hour
* Minute
* Second
I had to look  in source code for find the options that allowed me change the the tooltips of hour box. So it's better put this on the docs
=> Update Documentation incrementing new options

src/js/actions.ts
=> fix useTwentyfourHour.

src/js/display/index.ts
=> Fixes #2466

src/js/tempus-dominus.ts
fixes https://github.com/Eonasdan/tempus-dominus/issues/2493
=> fix for disposing inline calendar gives an exception

src/js/datetime.ts
Fix #2539
- Fix template for 24H HourDisplay
- [* ] The PR is against the `development` branch
Bug Fix:
#2539 
=> Fix "undefined" when using 24H-Format

src/js/utilities/options.ts
fixes https://github.com/Eonasdan/tempus-dominus/issues/2550
=> make viewMode optional

src/docs/partials/examples/index.html, src/js/display/index.ts
- [ ✔️ ] The PR is against the `development` branch
- [ ✔️ ] Docs have been added / updated (for bug fixes / features)
- [ ✔️ ] Does NOT modify files under the "dist" folder.
Bug fix for #2596
The current behavior is to hide the toolbar and expand the width of the picker as expected to accommodate the clock next to the calendar but the clock itself is hidden (missing the css `show` class)
* **Does this PR introduce a …
=> fixing bug where side-by-side shows blank clock

.github/workflows/docs.yml
=> docs action

.github/workflows/docs.yml
=> docs action (#2660)

dist/locales/ar-SA.js, dist/locales/ar.js, dist/locales/de.js, dist/locales/es.js, dist/locales/fi.js, dist/locales/fr.js, dist/locales/it.js, dist/locales/nl.js, dist/locales/pl.js, dist/locales/ro.js, dist/locales/ru.js, dist/locales/sl.js, dist/locales/tr.js, src/docs/partials/change-log.html, src/locales/ar-SA.ts, src/locales/ar.ts, src/locales/de.ts, src/locales/es.ts, src/locales/fi.ts, src/locales/fr.ts, src/locales/it.ts, src/locales/nl.ts, src/locales/pl.ts, src/locales/ro.ts, src/locales/ru.ts, src/locales/sl.ts, src/locales/tr.ts
Added formatting to existing locales.
=> updated locale

src/docs/partials/plugins/customDateFormat.html
* **What kind of change does this PR introduce?**
Fixes typo in docs
=> [Documentation] Fix typo in docs

src/js/display/index.ts
To clean up its internal stuff, fixes: https://github.com/Eonasdan/tempus-dominus/issues/2959
=> make sure the popperInstance is destroyed
