- src/js/bootstrap-datetimepicker.js
- test/publicApiSpec.js
Adding option disallowReadOnly=true
This will allow the user to set disallowReadOnly=false to trigger the
show() function on a read-only/disabled element.
> Fixes #793 #764

- src/js/bootstrap-datetimepicker.js
I am updating my Rails GEM to version 4. In my usecase I want to use your picker for the following markup:
```html
<div class="input-group date datepicker">
<input id="demo_model_date_field" class="string date_picker optional form-control" type="text"
name="demo_model[date_field]" 
data-date-options="{"calendarWeeks":true,
"dayViewHeaderFormat":"YYYY MMMM",
"showTodayButton":true,  
"widgetPositioning":{"horizontal":"left","vertical":"bottom"},
"locale":"en"}"
>
<span class="input-group-btn">
<button class="btn btn-default" type="button">
<span class="glyphicon glyphicon-calendar"></span>
</button>
</span>
</div>
```
The version 3 of your picker worked with this usecase. Could you please merge this pull request.
> Fixed the options handling for componets

- .gitignore
- src/js/bootstrap-datetimepicker.js
Added option focusOnShow for disable auto focusing input field, if datetimepicker is shown. This will improve handling on mobile devices.
> fix #848, added option focusOnShow for disable auto focusing input field

- src/sass/_bootstrap-datetimepicker.scss
- src/sass/bootstrap-datetimepicker-build.scss
This fixes some missed less to sass translation (see #946).
Maybe also an idea to remove the bootstrap-datetimepicker-build.scss file and instead place the .sr-only class to the top of _bootstrap-datetimepicker.scss.
> Fixes missed less to sass translation

- src/js/bootstrap-datetimepicker.js
(Resubmit on development branch)
Hey,
I ran into a bug while using linked datepickers. When linking 2 datepickers as done in the example (http://eonasdan.github.io/bootstrap-datetimepicker/#linked-pickers) the event for dp.change contains an event.date = null which then causes problems for the min and maxDate(...) functions (Uncaught TypeError: minDate() Could not parse date parameter: null).
Here's a fiddle as well: http://jsfiddle.net/8qLje5sk/
Changing the dp.change event.date for setValue(null) to false instead of null seems to fix that problem, since it is then considered in l. 1436 (for picker.minDate). If for some reason setting date = false is not ok one could just change the said line to include minDate == null.
> Fixed null exception for linked fields

- src/js/bootstrap-datetimepicker.js
- test/publicApiSpec.js
Hi! I needed to override a function that is responsible for parsing the date. For example: the user can enter 'yesterday' or '30 days ago' and it should be formatted correctly in the desired date.
> Added option for customization parse function

- src/less/_bootstrap-datetimepicker.less
``.today`` marker wasn't visible because of invalid css-syntax in border property.
- - - -
> .today mark fixed

- package.json
Change name to match npm's name since the package is here: https://www.npmjs.com/package/eonasdan-bootstrap-datetimepicker
> Change name to match that of npm

- src/sass/_bootstrap-datetimepicker.scss
Add !default to sass variables, so its possible to define the variables before the datetimepicker sass is included in the sass file.
Then the datetimepicker sass uses my own variables (if defined), and won't override it with its own.
If you don't define your own variables, the defaults from datetimepicker will be used.
> add default! to sass variables

- Gruntfile.js
- src/less/bootstrap-datetimepicker-build.less
In favor of using the 'path' option of grunt-contrib-less.
When using Symfony2 and SpBowerBundle, the node_modules does not exist.
Having imports that are not tied to vendors locations allows us to compile .less files with this setup without breaking the default one for this project.
> Get rid of the ugly ../../node_modules in build/css/bootstrap-datetimepicker.min.css

- docs/Options.md
The 'close' icon was missing from the 'icons' options hash in the docs, this adds it :+1:
> Add close icon to icons hash in docs.

- Gruntfile.js
- bower.json
- package.json
- src/js/bootstrap-datetimepicker.js
- test/screen-capture/base.html
Incorporating the functionality of moment-timezone, added a new option
called timeZone that allows setting the time zone of the picker rather
than relying on the client time zone settings, useful for situations
where you want to display the calendar dates/times in a time zone
regardless of what time zone the client is set.
At this point not sure how this should be incorporated, especially if timezone support isn't desired since the reliance on moment-timezone.
> Add ability to set time zone used by the datepicker

- build/css/bootstrap-datetimepicker-standalone.css
As discussed in this issue: https://github.com/Eonasdan/bootstrap-datetimepicker/issues/1199
I gave it a first try to create a standalone CSS file. It seems to work pretty good already, at least on a page with just the datetimepicker. I've tested both inline and dropdown variant.
It adds one dependency though: it requires the glyphicon font from Bootstrap.
> Ability to use the datetimepicker without the full Bootstrap CSS

- Gruntfile.js
- package.json
- src/js/bootstrap-datetimepicker.js
- test/publicApiSpec.js
- test/timezoneDataHelper.js
- Removed the before/after timezone check in `getMoment()` and always apply `.tz()` #1326 
- Simplified the code in `getMoment()`
- Created a `hasTimeZone()` private function
- `setValue` now sets the timezone on the given moment to display the date in the given `options.timeZone`
Test case:
- Added a dependency on `grunt-contrib-connect` : the jasmine tests are now hosted on a temporary local web server in order to be able to load the `moment-timezone`'s JSON data file.
- Added a dependency on `grunt-env` : Lets me choose the time zone used by PhantomJS for the jasmine tests.
- Added a test case for the bug #1326
> fixed timezone shift in some cases + added test case. Fixes #1326

- src/js/bootstrap-datetimepicker.js
I hit this in a current project using the latest release and I want to resolve #1185 to update the logic used for active and disabled states of the decades in the picker. This change will allow for the decade that contains the specified minDate to be enabled and active. This should also resolve #1181 and resolve #1170
jsfiddle: https://jsfiddle.net/ambLgwx4/3/
> Fix #1185: Bug: disabled year range that the selected year belongs to

- src/js/bootstrap-datetimepicker.js
setValue(targetMoment) trimmed the excess minutes when rounding using stepping. This caused an hour offset when rounding up to or over 60 minutes, see this JSFiddle:
http://jsfiddle.net/gjcwzpgp/
Removing the trimming was enough, momentJS bubbles up the hour if necessary.
> Don't trim the minutes overflow when rounding in #setValue(value)

- docs/Events.md
- src/js/bootstrap-datetimepicker.js
Now that keepInvalid is possible it is also possible that an invalid entry causes a *change*.
Use case:
Developer sets keepInvalid=true and wishes to revert date back to previous value based the invalid entry.
Justification:
When keepInvalid=true an actual change occurs to the value which implies that a dp.change event should be fired.
> Fire dp change on invalid entry if keep invalid is true

- docs/Events.md
- src/js/bootstrap-datetimepicker.js
Provide oldDate (previous value) on dp.error event.  Useful if keepInvalid=true because the previous value would otherwise have been lost.
Use case:
Set keepInvalid=true then only allow certain words to be saved, otherwise revert value back to original date.
Developer wishes to allow dates or specific words such as *Present*. For example, when filling out a job history form, the most recent job may be the current job therefore an *End Date* does not make sense but the word *Present* does.
Justification:
It would be ideal if the dp.change event fired on invalid entries (when keepInvalid=true) but it doesn't hurt to include the oldDate here.
> Provide oldDate (previous value) on dp.error event

- src/js/bootstrap-datetimepicker.js
- test/publicApiSpec.js
This plugin has the widest and most configurable API that I have seen for a date picker widget and the documentation is fantastic, simple, and clear. Thank you!
That said; I noticed a slight abnormality with how to access this API. It's become almost a standard for top jQuery plugins to expose their API via the plugin method itself. For example;
``` javascript
// initialize plugin with default options
$(element).datetimepicker()
// initialize plugin with custom options on top of the defaults
$(element).datetimepicker({ locale: 'fr' })
// get a value
$(element).datetimepicker('date')
// set a value
$(element).datetimepicker('date', moment())
// perform a single action
$(element).datetimepicker('toggle')
// perform a chain of actions
$(element)
.datetimepicker('show') …
```
> Clean method invocation

- package.json
Currently, using a jQuery version newer than 2.2 is not allowed. This change makes it less restrictive.
Also, allows Moment versions newer than 2.10.
> Reduce the jQuery and Moment version constraints

- src/js/bootstrap-datetimepicker.js
Fixed issue with Webpack and other build tools that use require or import.  The datetimepicker needs to be exported for these tools to work.  The code branch I modified should only be hit if the user is using a build tool like Webpack.
Fix directly taken from this issue: (thanks @melanke)
https://github.com/Eonasdan/bootstrap-datetimepicker/issues/1532
Should also fix: https://github.com/Eonasdan/bootstrap-datetimepicker/issues/1319
> Added module.exports

- src/js/bootstrap-datetimepicker.js
Pressing 'control space' when the picker is not active causes an error in the console. Most other keyBinds have an extra check to see if the widget is present. This pull request simply adds the same check to 'control space' to get rid of the runtime error.
> Fix 'control space' crash when widget is not present

- src/sass/_bootstrap-datetimepicker.scss
A plus sign has sneaked into the sass source, this PR just removes that, so the sass source works again.
> remove rouge + from sass source

- src/js/bootstrap-datetimepicker.js
This commit fixes an issue with stepping and minDate (issue #1065). If the current moment is rounded down to the nearest stepping, but that value is below minDate, the current date cannot be immediately clicked. Additionally, no value would be pre-populated in the datetimepicker input box.
> Fix issue #1065: Can't use minDate with stepping

- src/js/bootstrap-datetimepicker.js
- test/publicApiSpec.js
This change allows the user to customize the styles used for individual days in the calendar.  This allows the calendar to provide contextual information about each day to the end user.
For example, if used in a reservation application, days which are heavily booked could be styled differently than days which are almost entirely empty.  If used in an appointment calendar application, it could be used to indicate days in which there are possible conflicts for the specified appointment time (without preventing the date from being selected anyway).
> Allow the user to style individual calendar days

- src/js/bootstrap-datetimepicker.js
Calling `.datetimepicker()` on a list of elements causes them to share
options, which causes issues when using data attributes to configure
datetime pickers, as pickers will get the options of the datepickers
before them in the document.
JSFiddle showing bug: https://jsfiddle.net/r4z0rw0lf/LL2xx879/1/
> Make datepickers not share options

- src/js/bootstrap-datetimepicker.js
The internal `getMoment()`-function is forcing dates passed to `viewDate()` to be parsed with the local timeformat even if no format is set (see `actualFormat` in `initFormatting()`). When the datetimepicker is playing together with other components in the larger scope of a page, it can be meaningful to pass in these dates as Javascript `Date`-objects.
This change allows passing `Date()`-objects to `viewDate`.
The problem is illustrated in the [this JSfiddle](http://jsfiddle.net/06mhpqdL/5/).
> Allow passing a Date()-object to `viewDate()`

- src/js/bootstrap-datetimepicker.js
Export line inside factory function had not restrictive enough check that may
caused global namespace polluting problem during Karma test. Karma has a
`window.module` alias for `angular.mock.module` method used during tests. And as
a result other libs that may check for CommonJS env could erroneously try to use
`require` method which is non-existing in browser env. Example:
``` javascript
if (typeof module !== 'undefined' && module.exports) {
// CommonJS
module.exports = factory(require('angular'));
}
```
On the other hand this assignment inside factory function was overwritten by
the outcome of factory function itself in following line:
``` javascript
module.exports = factory(require('jquery'), require('moment'));
```
As a result when we had tried to …
> Fix CommonJS export

- package.json
Should work out of the box. 
Did run the `eval npm install` and didn't see any problem with running Jquery 3.0 and above with the Bootstrap 3 Date/Time Picker.
> Add support for Jquery ^3.0 in package.json

- src/js/bootstrap-datetimepicker.js
Love this picker. When I used it in my project, I found something amiss. 
When you initialize the plugin with inline as true (only) there is no external way of changing the view. By default it shows up the datepicker. Hence if I want to change the view to a timepicker my only option is to trigger a click on the span element which shows the time icon. 
I've noticed that there is no api to this effect. So I have added it.
The api call is `setInlineView` - it should be called with one argument (string) - either `datepicker` or `timepicker`
Running plunk: http://plnkr.co/edit/C0TbwenqXLboaVk1e2ta?p=preview
> added api to programmatically change the view in inline mode

- src/js/options.ts
Many JavaScript frameworks and bundlers minify code when building for production.
Minification includes renaming identifiers, including class names.
Comparing types using literal string names doesn't work well with these frameworks and bundlers.
For example, SvelteKit renames `DateTime` to something like `Ve`.
With this, the `if` test fails because 'Ve' is not the same as 'DateTime'.
This results in exceptions such as the following:
- Error: TD: Could not correctly parse "Sun Oct 03 2021 11:15:46 GMT+0000 (Coordinated Universal Time)" to a date for defaultDate
- Error: TD: Could not correctly parse "Sun Oct 03 2021 11:15:46 GMT+0000 (Coordinated Universal Time)" to a date for viewDate
With this change, in the minified file, the line now tests for `Ve.name` instead of 'DateTime'
> Compare date types with strongly typed names

- src/js/display/index.ts
fixes https://github.com/Eonasdan/tempus-dominus/issues/2493
when a reshow is done, especially with inline calender
the useCurrent or useDefault should not be used if there is already
someting in the dates.
If there is already a date set, but then you update some options it
should stick to that date, not reset to the current or default..
> fix reshow should not call dates.setValue with the current

- src/js/display/index.ts
- Create SVG elements in correct namespace
- Add standard `href` tag to `use` element. Maintain deprecated `xlink:href` for backward compatibility.
See:
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href
https://svgwg.org/svg2-draft/linking.html#XLinkRefAttrs
> Fixes use of SVG icons (issue #2527)

- src/js/tempus-dominus.ts
This PR triggers a native change event on an underlying input when available.
When an `input` element is updated, a native change event should be triggered. This allows client code to exist without needing explicit knowledge of the date picker used under the hood. Many change events (validation, chaining updates from one input to another, etc.) can and should be agnostic to the plugins (if any) that drive them.
This PR retains the default namespaced events to avoid a breaking change as well as allow plugin specific listeners.
> Trigger native change event on input when available - fixes #2401

- src/locales/ar-SA.ts
- src/locales/ar.ts
- [✓ ] The PR is against the `development` branch
- [ ✓] Does NOT modify files under the "dist" folder.
* **What kind of change does this PR introduce?** 
updates & improvements
adding Arabic locale
the arabic translation should appear correctly
No
> [IMP] adding support for Arabic locales

- src/locales/pl.js
Locale.
No polish locale.
Polish locale added.
No.
Please merge :-)
> Polish localization file pl.js

- src/docs/partials/options/display.html
- src/js/display/index.ts
- src/js/utilities/default-options.ts
- src/js/utilities/optionProcessor.ts
- src/js/utilities/options.ts
- [✔︎] The PR is against the `development` branch
- [✔︎] Docs have been added / updated (for bug fixes / features)
- [✔︎] Does NOT modify files under the "dist" folder.
This adds a feature to specify the initial placement for the widget when not inline. 
Although Popper JS seems to handle the placement of the widget every other time, the initial placement was hardcoded to `bottom-*` in `src/js/display/index.js`. If the widget is towards the bottom of the page, the initial toggle will …
> adding placement option

- src/js/validation.ts
Bug fix.
When dealing with date range and selecting the same date as start/end date it causes an infinite loop and browser crash.
As the problem was because of assuming that end date is always after start date, the start date was being incremented by 1 day before the for loop compare with the end date happens, causing the start date to be after the end date if it was the same day, hence the infinity loop.
The fix separates the increment from the initialization of the start variable and comparing if it's the same before the …
> fixing infinity loop bug in date range

- src/js/display/time/time-display.ts
Add `type='button'` attribute to meridiem `button` element to toggle AM/PM
Resolves the current behavior described at https://github.com/Eonasdan/tempus-dominus/issues/2820
Always add `type='button'` attribute to meridiem `button` element to toggle AM/PM
No breaking change.
None
> Add type attribute to meridiem button

- src/js/locales/fi.ts
Renamed Edelline -> Edellinen
FixesTypo in finnish localization.
PreviousYear was written with "Edelline," which is missing the last letter "n."
Fixed the typo in PreviousYear "Edelline" -> "Edellinen" 
No
> Fix typo in Finnish locale (previousYear in fi.ts)

- src/js/tempus-dominus.ts
Adds proposed changes from https://github.com/Eonasdan/tempus-dominus/issues/2871
The referenced configuration in the above issue fails to parse HTML input value.
Untested. Hopefully fixes the issue.
No
N/A
> Enabled code path for parsing multiple dates when date picker is in date range mode

- src/js/tempus-dominus.ts
Probably this changes should be in V7. If this is the case, I will do the changes just le met know.
see issue:
#2877 
…
N/A
No
> Fix where minDate would be a reference of viewDate instead of declaring it's own date

- src/js/locales/cs.ts
Wrong locale (de => cs)
Bug fix
Current locale is 'de'
New locale is 'cs'
No
> Fix 'cs' locale

- src/js/locales/pt-PT.ts
"2-digits" is wrong and should be "2-digit". See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/DateTimeFormat
It crashes in latest Chrome as is.
This is a simple fix because Portuguese currently crashes Chrome latest version when attempting to format because it uses the wrong format name for year.
> Update pt-PT.ts to fix year format
